services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.06.0
    hostname: pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - "8080:80/tcp"
    environment:
      - TZ=America/Los_Angeles
      - WEBPASSWORD_FILE=pihole_webpw
      - FTLCONF_webserver_interface_theme=default-auto
      - FTLCONF_dns_upstreams=unbound#53
      - FTLCONF_BLOCK_ICLOUD_PR=true
      - FTLCONF_dns_listeningMode=all
    volumes:
      - etc_pihole:/etc/pihole
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    secrets:
      - pihole_webpw
    restart: unless-stopped
    networks:
      - pihole
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: mvance/unbound${UNBOUND_IMAGE_SUFFIX}:1.22.0
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    restart: unless-stopped
    networks:
      - pihole

secrets:
  pihole_webpw:
    file: webpassword

volumes:
  etc_pihole:

networks:
  pihole:
    driver: bridge
