services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.03.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - "8080:80/tcp"
    environment:
      - TZ=America/Los_Angeles
      - FTLCONF_dns_interface=192.168.50.10
      - WEBPASSWORD_file=pihole_webpw
      - FTLCONF_webserver_interface_theme=default-auto
      - FTLCONF_dns_upstreams=unbound#5335
      - FTLCONF_dns_revServers=true,192.168.50.0/24,192.168.50.1:53,local
      - FTLCONF_dns_listeningMode=single
      - FTLCONF_BLOCK_ICLOUD_PR=false
    secrets:
      - pihole_webpw
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound:1.12.0
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    volumes:
      - ./unbound-conf:/opt/unbound/etc/unbound
    restart: unless-stopped

secrets:
  pihole_webpw:
    file: webpassword
