version: '3'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:2022.11.1
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      TZ: America/LosAngeles
      FTLCONF_REPLY_ADDR4: 192.168.0.10
      WEBPASSWORD_FILE: /run/secrets/pihole_webpw
      HOSTNAME: pihole
      DOMAIN_NAME: pihole.local
      WEBTHEME: default-auto
      #DNSSEC: true
    secrets:
      - pihole_webpw
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped

secrets:
  pihole_webpw:
    file: webpassword
