version: '3'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole
    image: ghcr.io/nickzelei/pihole-unbound:2023.11.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    ports:
      #- 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - "8080:80/tcp"
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - TZ=America/LosAngeles
      - FTLCONF_LOCAL_IPV4=192.168.0.10
      - WEBPASSWORD_FILE=/run/secrets/pihole_webpw
      - WEBTHEME=default-auto
      - PIHOLE_DNS_=127.0.0.1#5335
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_TARGET=192.168.0.1
      - REV_SERVER_CIDR=192.168.0.0/24
      - DNSMASQ_LISTENING=single # needed for exposure to other devices on network
      - FTLCONF_BLOCK_ICLOUD_PR=false
    secrets:
      - pihole_webpw
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
      - ./custom-dns.list:/etc/pihole/custom.list
    restart: unless-stopped

secrets:
  pihole_webpw:
    file: webpassword
